### ISSUE TITLE
Icon / Image for notification

### ISSUE THREAD

**Issue by gsantner** [David-Lor/MQTT2NotifySend#3]
Hello! 
Just saw you mentioned potential upcoming support for icon.
Can you please also consider setting icon via a separate key having a base64 string value? Would be nice to be able to set e.g. a music cover image on sender and show it on desktop.
When using notify-send executable it's gonna be needed to temporary write the img to temporary file

So e.g. "icon" and "icon_base64" keys

**Comment by David-Lor** [comment]
Yeah, I though about that. I'll keep this opened until implemented (:

**Comment by David-Lor** [comment]
(exactly) 2 years later... done! :sweat_smile:
