### ISSUE TITLE
Running without having Terminal Open

### ISSUE THREAD

**Issue by shaunvdp** [David-Lor/MQTT2NotifySend#6]
@David-Lor  Hi there. Awesome piece of code. any chance this can be run without the need to keep the terminal window open and to autostart at boot?

**Comment by David-Lor** [comment]
Hello there!

Some ways to achieve what you want, that I can think of:

- Run the script with a `&` at the end, for making it work at background (https://linuxize.com/post/how-to-run-linux-commands-in-background/).
- Create another script that calls the mqtt2notifysend script with your parameters, then make it executable and double-click it for opening in background (or run in terminal with `&` at the end).
- Make the script with arguments be called upon boot or login (e.g. with cron: https://phoenixnap.com/kb/crontab-reboot). Your desktop environment (Gnome, KDE, XFCE, whatever) may also feature a way for running custom commands when you log in (e.g. on Gnome: https://help.gnome.org/users/gnome-help/stable/shell-apps-auto-start.html.en)
